models:
  - name: customer_revenue
    columns:
      - name: customer_name
        tests:
          - string_not_empty
  - name: products
    columns:
      - name: name
        tests:
          - string_not_empty
  - name: customers
    columns:
      - name: name
        tests:
          - string_not_empty
  